package myP;


import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import oracle.jdbc.pool.OracleDataSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Discovery
 */
public class Boorowed_Books extends javax.swing.JFrame {

    /**
     * Creates new form Boorowed_Books
     */
    public Boorowed_Books() {
        initComponents();
        t44.setVisible(false);
        t55.setVisible(false);
        l1.setVisible(false);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t44 = new javax.swing.JTextField();
        t55 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        PDF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrowed books info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(153, 0, 0))); // NOI18N

        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setForeground(new java.awt.Color(153, 0, 0));
        save.setText("Borrow");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete.setForeground(new java.awt.Color(153, 0, 0));
        delete.setText("Return");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        search.setForeground(new java.awt.Color(153, 0, 0));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 0));
        jButton6.setText("Show All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Participants id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("ISBN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Date of borrow");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Date of return");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("id");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Delay");

        t6.setEditable(false);
        t6.setBackground(new java.awt.Color(255, 255, 255));

        l1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        l1.setText("Pay Tax !!");

        PDF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PDF.setForeground(new java.awt.Color(153, 0, 0));
        PDF.setText("PDF");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(t2)
                                    .addComponent(t44)
                                    .addComponent(t55)
                                    .addComponent(t1))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(save)
                                                .addComponent(jButton6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(8, 8, 8)))
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PDF)
                            .addComponent(jButton1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(delete))
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PDF)
                .addGap(88, 88, 88))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 0, 370, 630);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 120, 610);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 0, 200, 610);

        setSize(new java.awt.Dimension(680, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(url, "C##teama", "123456");
            Statement stmt=con.createStatement(); Statement stmt2=con.createStatement();
             try{
              String sDate1=t44.getText(); //String sDate2=t55.getText();
              Date datee1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);  
              //Date datee2=new SimpleDateFormat("yyyy-MM-dd").parse(sDate2); 
              SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);//MM/dd/yyyy
              Date d1=datee1;
              Date d2=date2.getDate();
              long diffm = Math.abs(d2.getTime() - d1.getTime());
              long diff =TimeUnit.DAYS.convert(diffm, TimeUnit.MILLISECONDS);
              if(diff<=10)t6.setText("0");
              else{
                  long lay = diff - 10;
                  t6.setText(String.valueOf(lay)+ " days late");
                  l1.setVisible(true);
              }
              
              
                }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
                  } 
         //   String string = null;
String string ="update BORROWEDBOOK set BOOKID="+this.t1.getText()+",PARTICIPANTSID="+this.t2.getText()+",ISBN='"+this.t3.getText()+",delay='"+"' where BOOKID='"+this.t1.getText()+"'  ";
           // string = "', delay='"+"update borrowed_books set book_ID="+this.t1.getText()+",part_id="+this.t2.getText()+",book_isbn='"+this.t3.getText()+"',date_return='"+((JTextField)date2.getDateEditor().getUiComponent().getText()+t6.getText()+"' where book_ID='"+this.t1.getText()+"'  ";
            String sql="update BOOKS set STATUS='Available' where ISBN= '"+this.t3.getText()+"' ";
            stmt.executeUpdate(string);
            stmt2.executeUpdate(sql);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Updated!");
        } catch (SQLException ex) {
            Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1522:orcl";
            Connection con=DriverManager.getConnection(url, "C##teama", "654321");
            Statement stmt=con.createStatement(); Statement stmt2=con.createStatement();
            String string="delete from borrowed_books where book_id='"+this.t1.getText()+"' ";
            String sql="update books set status='Available' where isbn= '"+this.t3.getText()+"' ";
            stmt.executeUpdate(string);
            stmt2.executeUpdate(sql);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Deleted!");
        } catch (SQLException ex) {
            Logger.getLogger(EMPLOYEE.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
//         t55.setVisible(false); date2.setVisible(true);
        try {
                         // t44.setVisible(true); t55.setVisible(true);
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(url, "C##teama", "123456");
            Statement stmt=con.createStatement();
            String sql ="select * from BORROWEDBOOK where BOOKID= '"+this.t1.getText()+"' ";
            ResultSet rs =stmt.executeQuery(sql);
            while(rs.next()){
                String id =rs.getString(1);
                t1.setText(id);

                String fname=rs.getString(2);
                t2.setText(fname);

                String mname=rs.getString(3);
                t3.setText(mname);
                
              /*  String date11=rs.getString(4);
                date1.setVisible(false);
                t44.setText(date11);*/
                
               /* String date22=rs.getString(5);
                date2.setVisible(false);
                t55.setText(date22); */
                
             /*   String mnam=rs.getString(6);
                t6.setText(mnam);*/
                
            } /*    if(date1 != null){
                   try{
              String sDate1=t44.getText(); String sDate2=t55.getText();
              Date datee1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);  
              Date datee2=new SimpleDateFormat("yyyy-MM-dd").parse(sDate2); 
              SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);//MM/dd/yyyy
              Date d1=datee1;
              Date d2=datee2;
              long diffm = Math.abs(d2.getTime() - d1.getTime());
              long diff =TimeUnit.DAYS.convert(diffm, TimeUnit.MILLISECONDS);
              t6.setText(String.valueOf(diff));
              
                }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
                  }
            }*/
            con.close();
           JOptionPane.showMessageDialog(null, "Searched!");
        } catch (SQLException ex) {
            Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          try {     
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(url, "C##teama", "123456");
            Statement stmt=con.createStatement(); Statement stmt2=con.createStatement();
              Object date2 = null;
            String string ="insert into BORROWEDBOOK values ("+this.t1.getText()+","+this.t2.getText()+", '"+this.t3.getText()+"' )  "; /*'"+((JTextField)date1.getDateEditor().getUiComponent()).getText()+"'*/
            if(date2 != null){
               t6.setText("0");
            }
            String stringg ="insert into BORROWEDBOOK values ("+this.t1.getText()+","+this.t2.getText()+", '"+this.t3.getText()+"' )  "; /*'"+((JTextField)date1.getDateEditor().getUiComponent()).getText()+"'*/
             // String string = null;
       
            stmt.executeUpdate(string);
            String sql="update BOOKS set STATUS='Borrowed' where ISBN= '"+this.t3.getText()+"' ";
            stmt2.executeUpdate(sql);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Saved!");
            
        } catch (SQLException ex) {
            Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 dispose();
                Home frame = new Home();
                frame.setVisible(true);
                frame.setSize(700, 587);

            }
        }); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 dispose();
                ShowallBoorowed frame = new ShowallBoorowed();
                frame.setVisible(true);
                frame.setSize(888, 424);

            }
        });*/
        try{
               DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(url, "C##teama", "123456");
            Statement stmt=con.createStatement();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    dispose();
                    SBR frame = new SBR();
                    frame.setVisible(true);
                    frame.setSize(700, 587);

                }
            });

            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(url, "C##teama", "123456");
            Statement stmt=con.createStatement();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    dispose();
                    pdf frame = new pdf();
                    frame.setVisible(true);
                    frame.setSize(800, 587);

                }
            });

            con.close();
      /*      OracleDataSource ods=new OracleDataSource();  
            
           ods.setUser("C##teama");
           ods.setPassword("123456");
           
          ods.setURL("jdbc:oracle:thin:@localhost:1521:xe");
          Connection LibraryProject=ods.getConnection();
          InputStream input=new FileInputStream(new File("Borrowed_Book_table.jrxml"));
          JasperDesign jd=JRXmlLoader.load(input);
          JasperReport jr=JasperCompileManager.compileReport(jd);
          JasperPrint jp=JasperFillManager.fillReport(jr, null, LibraryProject);
         OutputStream os= new FileOutputStream(new File("Borrowed_Book.pdf"));
          JasperExportManager.exportReportToPdfStream(jp, os);
          os.close();
          input.close();*/
}
catch(Exception e){
JOptionPane.showMessageDialog(null,"Check file details");
}
// TODO add your handling code here:
    //    } catch (SQLException ex) {
      //      Logger.getLogger(Boorowed_Books.class.getName()).log(Level.SEVERE, null, ex);
       // } catch (FileNotFoundException ex) {
        //    Logger.getLogger(Boorowed_Books.class.getName()).log(Level.SEVERE, null, ex);
       // } catch (JRException ex) {
         //   Logger.getLogger(Boorowed_Books.class.getName()).log(Level.SEVERE, null, ex);
       // } catch (IOException ex) {
        //    Logger.getLogger(Boorowed_Books.class.getName()).log(Level.SEVERE, null, ex);
       // }
    }//GEN-LAST:event_PDFActionPerformed
       /* try{
              String sDate1=t44.getText(); String sDate2=t55.getText();
              Date datee1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);  
              Date datee2=new SimpleDateFormat("yyyy-MM-dd").parse(sDate2); 
              SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);//MM/dd/yyyy
              Date d1=datee1;
              Date d2=datee2;
              long diffm = Math.abs(d2.getTime() - d1.getTime());
              long diff =TimeUnit.DAYS.convert(diffm, TimeUnit.MILLISECONDS);
              t6.setText(String.valueOf(diff));
              
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }*/
        
    /* try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1522:orcl";
            Connection con=DriverManager.getConnection(url, "C##teama", "654321");
            Statement stmt=con.createStatement();
            String string ="update borrowed_books set book_ID="+this.t1.getText()+",part_id="+this.t2.getText()+",book_isbn='"+this.t3.getText()+"',date_borrow='"+((JTextField)date1.getDateEditor().getUiComponent()).getText()+"',date_return='"+((JTextField)date1.getDateEditor().getUiComponent()).getText()+"' where book_ID='"+this.t1.getText()+"'  ";
            stmt.executeUpdate(string);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Updated!");
        } catch (SQLException ex) {
            Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    /**
     * @param args the command line arguments
     */
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PDF;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t44;
    private javax.swing.JTextField t55;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
