
package myP;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.awt.Image;

import java.awt.Label;


/**
 *
 * @author Discovery
 */
public class NewJFrame extends javax.swing.JFrame implements Runnable {
   Connection con;
   int s=0;
   Thread th;
   
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        super("Loading");
        initComponents();
        th= new Thread((Runnable)this);
        setUpLoading();
        
       
        
        
        
        
    }
    
    public void scaleImage(){
        
        ImageIcon ii = new ImageIcon(getClass().getResource("/img/kak.jpg"));
               
       Image image = (ii).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
       
      ii = new ImageIcon(image);
       jLabel1.setIcon(ii);
        
        
        
    }
            
            
            
            
    public void setUpLoading(){
        setVisible(false);
        th.start();
        
    }
    public void run(){
        try{
            for(int i=0;i<200;i++){
                s=s+1;
                int m=bar.getMaximum();
                int v=bar.getValue();
                if(v<m){
                    bar.setValue(bar.getValue()+1);
                } else{
                    i=201;
                   // JOptionPane.showMessageDialog(null, "hi");
                    setVisible(false);
                    Login ob=new Login();
                    ob.setVisible(true);
                } Thread.sleep(50);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(6000, 2000));
        getContentPane().setLayout(null);

        bar.setForeground(new java.awt.Color(0, 0, 255));
        bar.setStringPainted(true);
        getContentPane().add(bar);
        bar.setBounds(20, 290, 330, 14);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   NNU LIBRARY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 240, 290, 60);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 230, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nnu_logo.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nnu_logo.png"))); // NOI18N
        jButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton2StateChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 10, 110, 70);
        jButton2.getAccessibleContext().setAccessibleName(".");
        jButton2.getAccessibleContext().setAccessibleDescription(".");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/a08e4ecd-ff7d-425d-803e-41e45e7c706e (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-280, -290, 1260, 1020);

        setSize(new java.awt.Dimension(632, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        Desktop NewJFrame =Desktop.getDesktop();
        try{
       NewJFrame.browse(new URI("https://www.najah.edu/en/")); 
    }//GEN-LAST:event_jButton2ActionPerformed
       catch(IOException err){
           
           
       }
        catch (URISyntaxException err){
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* NewJFrame f= new NewJFrame ();
        f.setUpLoading();*/
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}